#!/bin/bash
# vim:fdm=marker
set -ex

# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Constants {{{
mod="Mod4"
alt="Mod1"
ctrl="Control"
lv3="Mod5"

# touchpad="10182:500:GDX1515:00_27C6:01F4_Touchpad"
if [[ "$MACHINE" == "vivo" ]]
then
    touchpad="pointer-10182-500-GDX1515:00_27C6:01F4_Touchpad"
elif [[ "$HOSTNAME" == "a13" ]]
then
    # a13
    touchpad="pointer-1267-12725-ELAN0798:01_04F3:31B5_Touchpad"
fi
waylanddir="$HOME/.local/share/wayland"

map="riverctl map -layout 0"
# }}}
# Desktop config {{{
# Set background and border color
# riverctl background-color 0x002b36
riverctl background-color 0x080808
# riverctl border-color-focused 0x93a1a1
# riverctl border-color-unfocused 0x586e75
riverctl border-width 0

# }}}
# DBus environment {{{
# exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE || true
dbus-update-activation-environment || true
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river || true
# }}}

# System hotkeys {{{
# Mod+Shift+E to exit river
$map normal $mod+$ctrl Q exit

# Lock screen
$map normal $ctrl+$alt L spawn 'swaylock -i ~/.wallpapers/332450.jpg'
# }}}
# App hotkeys {{{
# Mod+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
# $map normal $mod+Shift Return spawn foot
$map normal $mod Return spawn alacritty
$map normal $mod r spawn "rofi -show run"
$map normal $mod n spawn networkmanager_dmenu
$map normal $mod o spawn "$waylanddir/okta.py"
$map normal $mod o spawn "$waylanddir/okta.py"
# }}}
# Media keys {{{
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    $map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    $map -repeat $mode None XF86AudioRaiseVolume  spawn "$waylanddir/volume.sh 2%+"
    $map -repeat $mode None XF86AudioLowerVolume  spawn "$waylanddir/volume.sh 2%-"
    $map -repeat $mode None XF86AudioMute  spawn "$waylanddir/mute.sh"
    $map -repeat $mode None KP_Up    spawn "$waylanddir/volume.sh 2%+"
    $map -repeat $mode None KP_Down  spawn "$waylanddir/volume.sh 2%-"
    # $map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    $map $mode None KP_Begin spawn 'playerctl play-pause'
    $map $mode None KP_Left  spawn 'playerctl previous'
    $map $mode None KP_Right  spawn 'playerctl next'
    $map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    $map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    $map $mode None XF86AudioPrev  spawn 'playerctl previous'
    $map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brighness
    $map $mode None XF86MonBrightnessUp   spawn "$waylanddir/brightness.sh 2%+"
    $map $mode None XF86MonBrightnessDown spawn "$waylanddir/brightness.sh 2%-"

    $map $mode $mod p spawn "killall -s SIGINT wf-recorder"
done
# }}}
# Screenshot keys {{{
$map normal None Print spawn 'grim -o eDP-1 -t png - > /tmp/sshot.png && (wl-copy < /tmp/sshot.png && notify-send -i /tmp/sshot.png "Screen copied to clipboard") || notify-send "Terminated"'
$map normal $alt Print spawn 'grim -g "$(slurp)" -t png - > /tmp/sshot.png && (wl-copy < /tmp/sshot.png && notify-send -i /tmp/sshot.png "Selected area copied to clipboard") || notify-send "Terminated"'
# }}}
# Notification keys {{{
riverctl declare-mode dunst
# $map normal None Escape spawn "[[ \`dunstctl count displayed\` != \"0\" ]] && dunstctl close || (riverctl enter-mode dunst; wtype -P Escape; xdotool key Escape; riverctl enter-mode normal)"
$map normal $alt Escape spawn "[[ \`dunstctl count displayed\` != \"0\" ]] && dunstctl close"
# $map normal -passthrough None Escape spawn "[[ \`dunstctl count displayed\` != \"0\" ]] && dunstctl close"
# }}}

# Outputs {{{
# Disable touchpad display
wlr-randr --output HDMI-A-1 --off || true
[[ "$HOSTNAME" == "a13" ]] && wlr-randr --output eDP-1 --scale 1.6
$map normal $alt Tab focus-output next
$map normal $alt+Shift Tab send-to-output next
# }}}
# Window management {{{
# Alt+F4 to close the focused view
$map normal $alt F4 close

# Mod+J and Mod+K to focus the next/previous view in the layout stack
$map normal $mod Left focus-view previous
$map normal $mod Right focus-view next
$map normal $mod Tab focus-view next
$map normal $mod+$lv3 Left focus-view previous
$map normal $mod+$lv3 Right focus-view next
# $map normal $alt Tab focus-view next

# Mod+Shift+J and Mod+Shift+K to swap the focused view with the next/previous
$map normal $mod J swap next
$map normal $mod K swap previous

# Mod+Period and Mod+Comma to focus the next/previous output
# $map normal $mod Period focus-output next
# $map normal $mod Comma focus-output previous

# Mod+Shift+{Period,Comma} to send the focused view to the next/previous output
# $map normal $mod+Shift Period send-to-output next
# $map normal $mod+Shift Comma send-to-output previous

# Mod+Return to bump the focused view to the top of the layout stack
# TODO: Switch stacktile layout between full & columns
$map normal $mod Space send-layout-cmd stacktile 'primary_sublayout full,columns,grid'

# Mod+H and Mod+L to decrease/increase the main ratio of rivertile(1)
$map normal $mod H send-layout-cmd rivertile "main-ratio -0.05"
$map normal $mod L send-layout-cmd rivertile "main-ratio +0.05"

# Mod+Shift+H and Mod+Shift+L to increment/decrement the main count of rivertile(1)
$map normal $mod+Shift H send-layout-cmd rivertile "main-count +1"
$map normal $mod+Shift L send-layout-cmd rivertile "main-count -1"

# Mod+Alt+{H,J,K,L} to move views
$map normal $mod+$alt H move left 100
$map normal $mod+$alt J move down 100
$map normal $mod+$alt K move up 100
$map normal $mod+$alt L move right 100

# Mod+Alt+Control+{H,J,K,L} to snap views to screen edges
$map normal $mod+$alt+$ctrl H snap left
$map normal $mod+$alt+$ctrl J snap down
$map normal $mod+$alt+$ctrl K snap up
$map normal $mod+$alt+$ctrl L snap right

# Mod+Alt+Shif+{H,J,K,L} to resize views
$map normal $mod+$alt+Shift H resize horizontal -100
$map normal $mod+$alt+Shift J resize vertical 100
$map normal $mod+$alt+Shift K resize vertical -100
$map normal $mod+$alt+Shift L resize horizontal 100

# Mod + Left Mouse Button to move views
riverctl map-pointer normal $mod BTN_LEFT move-view

# Mod + Right Mouse Button to resize views
riverctl map-pointer normal $mod BTN_RIGHT resize-view

# Window modes
$map normal $mod X toggle-float
$map normal $mod F toggle-fullscreen
# }}}
# Tag management {{{
declare -A tag_map=([q]=1 [w]=2 [i]=4 [e]=4 [m]=8 [s]=8 [a]=16)

for key in ${!tag_map[@]}
do
    # tags=$((1 << ($i - 1)))
    tags=${tag_map[$key]}

    # Mod+[letter] to focus tag[1-5]
    $map normal $mod $key set-focused-tags $tags
    # Mod+Shift+[1-5] to tag focused view with tag [1-5]
    $map normal $mod+Shift $key set-view-tags $tags
done

# Mod+0 to focus all tags
# Mod+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
$map normal $mod 0 set-focused-tags $all_tags
$map normal $ctrl+Shift 0 set-view-tags $all_tags
# }}}
# Window rules (floating & CSD) {{{
# Make certain views start floating
# riverctl float-filter-add app-id float
# riverctl float-filter-add title "popup title with spaces"
# riverctl float-filter-add title "Media viewer"
# riverctl unfloat-filter-add title "Spotify"
# riverctl unfloat-filter-add app-id "Spotify"

# Set app-ids and titles of views which should use client side decorations
# riverctl csd-filter-add app-id "gedit"
riverctl rule-add csd -app-id "gedit"
riverctl rule-add float -title '*Покажчик спільного доступу*'
# }}}

# Mouse & touchpad {{{
# riverctl hide-cursor when-typing enabled

riverctl input $touchpad tap enabled
# riverctl input $touchpad scroll_factor
riverctl input $touchpad tap-button-map left-right-middle
riverctl input $touchpad click-method clickfinger
riverctl input $touchpad disable-while-typing disabled
# }}}
# Keyboard {{{
# Set keyboard repeat rate
riverctl set-repeat 25 167
riverctl keyboard-layout -options grp:alt_space_toggle us,ua
# }}}
