#!/bin/bash

PATH="/sh:/bin:/usr/local/bin:/sbin:/usr/local/sbin:/usr/bin/core_perl"
export EDITOR="nano"
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on'
export PATH="/usr/share/perl5/vendor_perl/auto/share/dist/Cope:/home/anderson/.npm-packages/bin:$PATH:/home/anderson/.gem/ruby/2.2.0/bin"
export TERM=screen-256color
# export COPE=1

export IDEA_JDK="/usr/lib/jvm/java-8-openjdk/"
export ANDROID_EMULATOR_USE_SYSTEM_LIBS=1
export STEAM_RUNTIME=0

export DMENU_STYLE="-fn 'DejaVu Sans Mono-10' -sb '#F05040' -sf '#000' -nb black -dim 0.5"

case $(tty) in /dev/tty[0-9]*)
    export TERM=linux ;;
esac
