#!/bin/bash

export EDITOR="nvim"
export BROWSER="firefox-developer-edition"
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on'
export GOPATH="/home/anderson/src/go"
export PATH="$PATH:$HOME/.scripts:/sh:$GOPATH/bin"
#export PATH="/usr/bin/vendor_perl/:$PATH"
# export PATH="/usr/share/perl5/vendor_perl/auto/share/dist/Cope:$PATH"
# export TERM=screen-256color
# export COPE=1

# export IDEA_JDK="/usr/lib/jvm/java-8-openjdk/"
export ANDROID_EMULATOR_USE_SYSTEM_LIBS=1
export STEAM_RUNTIME=0

export QT_SCALE_FACTOR=1.3

export DMENU_STYLE="-fn 'DejaVu Sans Mono-10' -sb '#F05040' -sf '#000' -nb black -dim 0.5"

export FZF_DEFAULT_COMMAND='ag -g . --skip-vcs-ignores --ignore __pycache__ --ignore .git --ignore "*".pyc'

case $(tty) in /dev/tty[0-9]*)
    export TERM=linux ;;
esac

export TTY=0
#export TERM=my-256color
export TERM=screen-256color

# GPG
export GPG_TTY=$(tty)

# GPMDP
export GPMDP_API_PORT=5673

case $(tty) in /dev/tty[0-9]*)
    export TTY=1 ;;
esac

export EXA_COLORS='da=38;5;193:uu=0:un=0:gu=0:gn=0:gm=38;5;32:sn=38;1;255'
export EXA_COLORS="$EXA_COLORS:ur=38;1;31:uw=38;1;31:ux=38;1;31:ue=38;1;31:gr=38;1;33:gw=38;1;33:gx=38;1;33:tr=38;1;32:tw=38;1;32:tx=38;1;32"
# export EXA_COLORS="uu=0:un=0:gu=0:gn=0"
# :di=4;38;5;111;1'

# export GTK_THEME=Numix:dark

export FrameworkPathOverride=/lib/mono/4.7.1-api/

export ANDROID_SDK=/home/anderson/Android/Sdk
export PATH="$PATH:$ANDROID_SDK/platform-tools:$ANDROID_SDK/tools"
