#!/bin/bash

function get_display_width {
    xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1
}

function get_display_height {
    xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2
}

function get_dmenu_pos {
    s=`xrandr --current | grep '*' | uniq | awk '{print $1}'`
    w=`echo $s | cut -d 'x' -f1`
    h=`echo $s | cut -d 'x' -f2`
    # w=`get_display_width`
    # h=`get_display_height`
    echo "-x $((w/2-200)) -y $((h/2-100)) -w 400 -h 200"
}

function cd() {
    builtin cd "${@}" && ll
}

# function feh() {
#     /usr/bin/feh --scale-down --auto-zoom --magick-timeout 5 "${@}"
# }

#function feh() {
#    if [[ -z "$1" ]]
#    then
#        path="*"
#    else
#        path="$1"
#    fi
#    sxiv $path
#}

function tg() {
    curl "https://api.telegram.org/bot${ARCHER_TG_TOKEN}/sendMessage" -H 'Content-Type: application/json' -d '{"text": "'"$@"'", "chat_id": "84560715"}'
}

function watchfile() {
    while true
    do
        inotifywait $1
        cat $1
    done
}

function j() {
    echo $1
    dir=$(FZF_DEFAULT_COMMAND="find $1 -type d" fzf)
    if ! [[ -z "$dir" ]]
    then
        cd "$dir"
    fi
}

function paste() {
    local file=${1:-/dev/stdin}
    curl --data-binary @${file} https://paste.rs
}

qkkdiff () {
	ver=$(pacman -Q $1 | cut -f2 -d' ')
	pacman -Qkkq $1 | while read package file
	do
		echo $file
		bsdtar -xOf /var/cache/pacman/pkg/${package}-${ver}-x86_64.pkg.tar.zst ${file/\//} | diff -uN - $file
	done
	return 0
}

qkkdiff-file () {
	pkg="$(pacman -Qo $1 | awk '//{printf "%s-%s", $(NF-1), $NF;}')"
	bsdtar -xOf /var/cache/pacman/pkg/${pkg}-x86_64.pkg.tar.zst ${1/\//} | diff -uN - $1
	return 0
}
