#!/bin/bash

if [[ "$SH" != "zsh" ]]
then
    _run()
    {
        local cur=${COMP_WORDS[COMP_CWORD]}
        local conns=`ls --color=never $HOME/.run`
        COMPREPLY=( $(compgen -W "$conns" -- $cur) )
    }
    complete -F _run run
fi

