#!/bin/bash

#ARROW=`echo -e "\ue0b0 "`
#ARROW=`echo -e "\ue0bc "`
ARROW=`echo -e ""`
ARROW=`echo -e "\e[38;5;238m\u23AA"`
#ARROW=`echo -e "\ue0d2 "`
#HOUSE=`echo -e "\u2302"`
#HOUSE=`echo -e "\uE614"`
#HOUSE=`echo -e "\uF015"`
HOUSE="~"
ROOT=`echo -e "\uE614"`
#PWD_SEP=`echo -e "\uF0DA"`
PWD_SEP="/"
PY_ICON=`echo -e "\uE606"`
ELLIPSIS=`echo -e "\u2026"`
case $(tty) in /dev/tty[0-9]*)
    ARROW=''; HOUSE=''; ROOT='' ;;
esac


# function is_chroot()
# {
#     [ "$(awk '$5=="/" {print $1}' </proc/1/mountinfo)" != "$(awk '$5=="/" {print $1}' </proc/$$/mountinfo)" ] && return 0 || return 1
# }


function make_prompt() {
    RETCODE=$?
    #START=$(echo -en "\uF2D0")
    START=""
    STAR=$(echo -en "\uF005")
    PULSE=$(echo -en "\uE234")
    #ARROW=$(echo -en "\uE0BC")
    GIT=$(echo -en "\uE725")
    #CODE=$(echo -en "\uF054")
    CODE=$(echo -en "\uE285")
    ROOT=$(echo -en "\uE614")
    LAST_BACK=""
    LAST_FORE=255
    LAST_FORE_MOD=0

    function fgcol() {
        echo -n "\[\e[38;5;$1m\]"
    }

    function fb() {
        FORE=$1
        BACK=$2
        FORE_MOD=${3:-0}
        if [[ "$4" == "-" ]]
        then
            ARROW=""
        fi
        #if [[ "$LAST_BACK" != "" && "$LAST_BACK" != "$BACK" ]]
        #then
        #    echo -n "\[\e[48;5;${BACK}m\]\[\e[38;5;${LAST_BACK}m\]$ARROW"
        #fi

        if [[ "$LAST_BACK" != "" ]]
        then
            echo -n "\[\e[48;5;${BACK}m\]\[\e[38;5;${LAST_BACK}m\]$ARROW"
        fi
        echo -n "\[\e[$FORE_MOD;38;5;${FORE}m\]"
        echo -n "\[\e[48;5;${BACK}m\]"
        printf -v "LAST_BACK" "$BACK"
        printf -v "LAST_FORE" "$FORE"
        printf -v "LAST_FORE_MOD" "$FORE_MOD"
    }

    function brk() {
        printf -v "LAST_BACK" ""
        #echo -e "\e[0;42m\e[K asd"
        echo
    }

    #function back() {
        #echo "$LAST_FORE_MOD;38;5;${LAST_FORE}m"
        #echo -n "\[\e[48;5;$1m\]\[\e[$LAST_FORE_MOD;38;5;${LAST_FORE}m\]"
    #}

    RST="\[\e[0m\]"

    function ssh_part() {
        if ! [[ -z "$SSH_CONNECTION" ]]
        then
            fb 0 255
            echo -n "$(hostname) "
        fi
    }

    function date_part() {
        #fb 255 125
        fb 32 234
        #date +" $START %H:%M:%S $RST" | tr -d '\n'
        date +"%H:%M:%S $RST" | tr -d '\n'
    }

    function venv_part() {
        if [[ ! -z "$VIRTUAL_ENV" ]]
        then
            #fb 255 22
            fb 28 234
            #fore 22
            #arrow
            echo -n ""
            #echo -en "$VIRTUAL_ENV $RST" | awk -F/ '{print $(NF-1)"/"$NF}' | tr -d '\n'
            echo -en " $PY_ICON env $RST"
        elif [[ -f ".env/bin/activate" ]]
        then
            VIRTUAL_ENV=$( . .env/bin/activate; echo $VIRTUAL_ENV )
            #fb 255 160
            fb 160 234
            echo -n ""
            #echo -en "$VIRTUAL_ENV $RST" | awk -F/ '{print $(NF-1)"/"$NF}' | tr -d '\n'
            echo -en " $PY_ICON env! $RST"
        fi
    }

    function git_part() {
        #BRANCH="$(git rev-parse --symbolic-full-name --abbrev-ref HEAD 2>&1) @ $(git rev-parse --short HEAD 2>&1)"
        BRANCH="$(git rev-parse --symbolic-full-name --abbrev-ref HEAD 2>&1)"
        #BRANCH="$(cat .git/HEAD | awk -F"refs/heads/" '{print $2}')"
        if [[ "$?" -eq "0" ]]
        then
            OUT=$(git status -s 2>&1)
            OIFS=$IFS
            if [ "${#BRANCH}" -gt 16 ]
            then
                BRANCH="${BRANCH::16}$ELLIPSIS"
            fi
            #IFS=$'\n'
            #for line in $(git st -s | sed -re 's/^\s+|\s+$//g')
            #do
                #echo "A${line}B"
            #done
            #IFS=$OIFS
            if [ "$OUT" == "" ]
            then
                #fb 255 28  # 28
                fb 41 234
                C=''
            else
                #fb 255 130
                fb 3 234
                C='!'
            fi
            UNPUSHED=$(git log origin/$BRANCH..HEAD --oneline wc -l 2> /dev/null | wc -l)
            echo -n " $GIT $BRANCH$C"
            if [[ "$UNPUSHED" -gt "0" ]]
            then
                fb 255 130
                echo -n " ($UNPUSHED pending commit)"
            fi
            echo -n " $RST"
        fi
    }

    function ret_part() {
        if [[ "$RETCODE" != "0" ]]
        then
            #fb 255 160
            fb 160 234 1
            echo -en "$RETCODE $RST"
            echo -en "\[$txtrst\]"
        fi
    }

    function dirs_part() {
        fb 255 31
        DIRS=$(find . -maxdepth 1 ! -path . -type d | wc -l)
        echo -en " \uE5FF $DIRS $RST"
    }

    function files_part() {
        fb 255 28  # 64
        FILES=$(find . -maxdepth 1 -type f -printf "%s\n")
        SIZE=$(echo $FILES | tr ' ' '+' | bc)
        SIZE=${SIZE:-0}
        SIZE=$(numfmt --to=iec-i --suffix=B --format="%.2f" $SIZE | sed -re "s/,00//g;s/([0-9])([A-Z])/\1 \2/g")
        # | tr -d "\n"
        echo -en " \uF15B $(echo $FILES | wc -w) ($SIZE) $RST"
    }

    function free_part() {
        fb 0 71
        echo -n " $(df -h / --output=avail | tail -n 1 | tr -d "\n ")iB free "
    }

    function pwd_part() {
        SPACE=`echo -e '\u2026'`
        fb 32 234 # 255 27 1
        #fb 197 234 # 255 27 1
        DIR=${PWD/$HOME/$HOUSE\/}
        DIR=${DIR/\//}
        DIR=${DIR// /$SPACE}
        IFS='/'
        PARTS=($DIR)
        CURRENT=0
        COUNT=${#PARTS[@]}
        if [[ "$PWD" == "/" ]]
        then
            fgcol 238
            echo -en " / $RST"
        else
            for PART in ${PARTS[@]}
            do
                CURRENT=$((CURRENT+1))
                if [[ "$CURRENT" != "$COUNT" ]]
                then
                    fgcol 32
                    echo -n " ${PART::3} "
                    fgcol 238
                    echo -n "$PWD_SEP"
                #elif [[ "$CURRENT" != "$COUNT" ]]
                #then
                #    fgcol 32
                #    echo -n " ${PART::3} "
                #    #fgcol 42
                #    fgcol 238
                #    echo -n "$PWD_SEP"
                #    #fb 32 234 0 -
                else
                    fgcol 32
                    echo -n " ${PART}"
                fi
            done
        fi
    }

    function pwd_part_old() {
        #fb 255 27 1
        if [[ "$PWD" == "/" ]]
        then
            fb 32 234 # 255 27 1
            echo -en " $ROOT $RST"
        else
            #echo $PWD
            DIR=${PWD/$HOME/$HOUSE\/}
            DIR=${DIR/\//}
            ##DIR=${DIR//\// \\uF44A }
            ##DIR=${DIR//\// \\uE0B1 }
            #DIR=${DIR//\// \\uE0BB }
            ##DIR=${DIR//\//  \\u258F }
            #echo -en "${DIR} $RST"
            OLD_IFS=$IFS
            IFS='/'
            NUM=100
            N=0
            COUNT=-1
            for _ in $DIR
            do
                COUNT=$((COUNT+1))
            done
            fb 32 234
            echo -n " "
            for i in $DIR
            do
                # Contrast colors
                for ((n=0; n<${#i}; n++ ))
                do
                    V=$(printf %d "'${i:$n:1}")
                    NUM=$((NUM+V))
                done
                NUM1=5
                NUM2=$NUM
                #NUM1=$N
                #NUM2=8
                BG=$((((NUM1%7)+1)*36-20 + NUM2%9))
                fb $BG 234
                echo -n "$i "
                #echo $N $COUNT
                if [[ "$N" != "$COUNT" ]]
                then
                    echo -n " " # "
                fi
                #echo -n a $i b
                #echo -n 1${i}${i}2
                N=$((N+1))
            done
            IFS=$OLD_IFS
        fi
    }


    function end_part() {
        fb 255
    }

    function dollar_part() {
        fb 32 0 1 -
        echo -n ' $'
    }

    ssh_part
    date_part
    venv_part
    git_part
    #dirs_part
    #files_part
    #free_part
    ret_part
    #end_part
    brk
    pwd_part
    #end_part
    #dollar_part
    echo -n " $RST "
}

function set_prompt() {
    #PS1="`info`"
    PS1="`make_prompt`"
    #PS1="`ret=$? /home/anderson/.config/qtile/bin/prompt.sh`"
    #PS1="`ret=$? /home/anderson/.config/qtile/bin/prompt.py`"
    # PS1="$hostname_result\[$bakblu\]\[$bldwht\] \w \[$txtrst\]$info_result "
}

# if [[ "$TTY" == "0" ]]
# then
#     PROMPT_COMMAND=set_prompt
# else
#     PROMPT_COMMAND=simple_prompt
# fi

export PYTHONIOENCODING=utf-8

PROMPT_COMMAND=set_prompt

function tag() {
    export TAG=$1
}

function make_zprompt() {
    ret=$? /home/anderson/.config/qtile/bin/zprompt.py
}

if [[ "$SH" == "zsh" ]]
then
    PS1='$(make_zprompt)'
fi

# PROMPT_COMMAND="~/.config/qtile/bin/prompt.py"

