#!/bin/bash

if [[ -x "$(command -v direnv)" ]]
then
    _direnv_hook() {
        local previous_exit_status=$?;
        trap -- '' SIGINT;
        eval "$("/usr/bin/direnv" export bash)";
        trap - SIGINT;
        return $previous_exit_status;
    };
    if ! [[ "${PROMPT_COMMAND:-}" =~ _direnv_hook ]]; then
        PROMPT_COMMAND="_direnv_hook;$PROMPT_COMMAND"
    fi
else
    echo -e "${bldred}Warning: direnv is not installed.${txtrst}"
fi
