icon: &icon
  font: 'RobotoMono Nerd Font:pixelsize=14'

bar:
  location: top
  height: 15
  font: RobotoMono Nerd Font:size=12
  background: 080808FF
  # background: 000000FF
  spacing: 10

  left:
    - script:
        path: /home/anderson/src/rivertags/rivertags
        args: []
        foreground: 'FFD78740'
        # foreground: '5FFF47FF'
        content:
          list:
            spacing: 4
            items:
              - map:
                  tag: tag1
                  values:
                    true:
                      - string: {text: "\uf68c", foreground: 'FF206FFF'}
                    false:
                      - string: {text: "\uf68c"}
              - map:
                  tag: tag2
                  values:
                    true:
                      - string: {text: "\ufa9e", foreground: 'FF206FFF'}
                    false:
                      - string: {text: "\ufa9e"}
              - map:
                  tag: tag3
                  values:
                    true:
                      - string: {text: "\ue217", foreground: 'FF206FFF'}
                    false:
                      - string: {text: "\ue217"}
              - map:
                  tag: tag4
                  values:
                    true:
                      - string: {text: "\uf6ed", foreground: 'FF206FFF'}
                    false:
                      - string: {text: "\uf6ed"}
              - map:
                  tag: tag5
                  values:
                    true:
                      - string: {text: "\uf11b", foreground: 'FF206FFF'}
                    false:
                      - string: {text: "\uf11b"}
    - foreign-toplevel:
        foreground: ffd787ff
        content:
          map:
            tag: activated
            values:
              false: {empty: {}}
              true:
                - map:
                    tag: app-id
                    default:
                      - string: {text: "\uFB13", <<: *icon}
                    values:
                      Alacritty: &alacritty
                        - string: {text: "\uF120", <<: *icon}
                      main: *alacritty
                      firefoxdeveloperedition:
                        - string: {text: "\uF269", <<: *icon}
                      telegramdesktop:
                        - string: {text: "\uF2C6", <<: *icon}
                      Spotify:
                        - string: {text: "\uF1BC", <<: *icon}
                - string: {text: " {app-id}"}
                - string: {text: " - {title}", foreground: ffffffff}
  center:
    - script:
        path: /home/anderson/.config/yambar/spectrum/spectrum
        args: [-l]
        # foreground: 'FFD78780'
        foreground: '5FFF47FF'
        font: Bars
        content:
          - string: {text: "{bar}"}
    - script:
        path: /home/anderson/.config/yambar/playerctl/playerctl
        content:
          - map:
              tag: playing
              values:
                true:
                  - string: {text: "\uF04B {title} {duration}", foreground: "5FFF47FF"}
                false:
                  - string: {text: "\uF04C {title} {duration}", foreground: "FFD78740"}
    - script:
        path: /home/anderson/.config/yambar/spectrum/spectrum
        args: [-r]
        # foreground: 'FFD78780'
        foreground: '5FFF47FF'
        font: Bars
        content:
          - string: {text: "{bar}"}
  right:
    # - river:
    #     title: {string: { text: "{seat} - {title}" }}
    #     content:
    #      map:
    #        tag: occupied
    #        values:
    #          false: {empty: {}}
    #          true:
    #            string:
    #              margin: 5
    #              text: "{id}: {state}"

    # - xkb:
    #     content:
    #       - string: {text: "{symbol}"}
    - script:
        path: /home/anderson/.config/yambar/weather.sh
        foreground: 'FFD787FF'
        content:
          - string: {text: "{icon}", font: "owfont", <<: *icon}
          - string: {text: " {temp}\u00B0"}
          - string: {text: " ({feels_like}\u00B0)"}
    - script:
        path: /home/anderson/.config/yambar/df.sh
        foreground: 'FFD787FF'
        content:
          map:
            tag: low
            values:
              true:
                - string: {text: "{icon}", foreground: 'DF206FFF', <<: *icon}
                - string: {text: " {value}", foreground: 'FF206FFF'}
              false:
                - string: {text: "{icon}"}
                - string: {text: " {value}"}
    - script:
        path: /home/anderson/.config/yambar/pulse/pulse
        foreground: 'AF87FFFF'
        content:
          - map:
              tag: headset
              values:
                true:
                  - string: {text: "\uF7CA", <<: *icon}
                false:
                  - string: {text: "\uF886", <<: *icon}
          - string: {text: " {volume}%"}
    - script:
        path: /home/anderson/.config/yambar/cpu.sh
        foreground: '5FD7FFFF'
        content:
          map:
            tag: high
            values:
              true:
                - string: {text: "{bar}", foreground: 'FF206FFF'}
                - string: {text: " {value}%", foreground: 'FF206FFF'}
              false:
                - string: {text: "{bar}"}
                - string: {text: " {value}%"}
    - script:
        path: /home/anderson/.config/yambar/networkmanager/networkmanager
        font: Bars
        content:
          - map:
              tag: state
              values:
                disconnected:
                  - string: {text: "\uF818", <<: *icon, foreground: "FF005FFF"}
                  - string: {text: " offline", foreground: "FF005FFF"}
                changing:
                  - string: {text: "\uF6D7", <<: *icon, foreground: "5FD7FFFF"}
                  - string: {text: " {network}", foreground: "5FD7FFFF"}
                connected:
                  - string: {text: "\uFAA8", <<: *icon, foreground: "5FD7FFFF"}
                  - string: {text: " {network}", foreground: "5FD7FFFF"}
    # - network:
    #     name: 'wlan0'
    #     content:
    #       # - map:
    #       #     tag: state
    #       #     default:
    #       #       string: {text: 'connecting'}
    #       #     values:
    #       #       up:
    #       #         string: {text: 'up'}
    #       #       down:
    #       #         string: {text: 'down'}
    #       - map:
    #           tag: carrier
    #           values:
    #             true:
    #               - map:
    #                   tag: state
    #                   default:
    #                     string: {text: "\uF6D7 {ssid}"}
    #                   values:
    #                     up:
    #                       string: {text: "\uFAA8 {ssid}"}
    #             false:
    #               - string: {text: "\uF818 offline"}
    - clock:
        foreground: FFD787FF
        time-format: "%d %b, %H:%M"
        content:
          - string: {text: "{time}"}
    - battery:
        name: BAT0
        poll-interval: 5
        anchors:
          discharging: &discharging
            list:
              items:
                - ramp:
                    tag: capacity
                    items:
                      - string: {text: ' ', foreground: ff0000ff}
                      - string: {text: ' ', foreground: ffa600ff}
                      - string: {text: ' ',}
                      - string: {text: ' ',}
                      - string: {text: ' ',}
                      - string: {text: ' ',}
                      - string: {text: ' ',}
                      - string: {text: ' ',}
                      - string: {text: ' ',}
                      - string: {text: ' ', foreground: 00ff00ff}
                - string: {text: " {capacity}%"}
        content:
          map:
            tag: state
            values:
              unknown:
                <<: *discharging
              discharging:
                <<: *discharging
              charging: &charging
                - string: {text: ' ', foreground: 00ff00ff}
                - string: {text: " {capacity}%"}
              full:
                - string: {text: ' ', foreground: 00ff00ff}
                - string: {text: " {capacity}%"}
              not charging: *charging
              # not charging:
              #   - ramp:
              #       tag: capacity
              #       items:
              #         - string: {text: '  ', foreground: ff0000ff}
              #         - string: {text: '  ', foreground: ffa600ff}
              #         - string: {text: '  ', foreground: 00ff00ff}
              #         - string: {text: '  ', foreground: 00ff00ff}
              #         - string: {text: '  ', foreground: 00ff00ff}
              #         - string: {text: '  ', foreground: 00ff00ff}
              #         - string: {text: '  ', foreground: 00ff00ff}
              #         - string: {text: '  ', foreground: 00ff00ff}
              #         - string: {text: '  ', foreground: 00ff00ff}
              #         - string: {text: '  ', foreground: 00ff00ff}
              #   - string: {text: " {capacity}%"}
